version: '3'

services:
  influxdb:
    image: influxdb
    container_name: influxdb_container
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin_password
      - INFLUXDB_USER=myuser
      - INFLUXDB_USER_PASSWORD=mypassword

  grafana:
    image: grafana/grafana
    container_name: grafana_container
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
      - GF_SECURITY_ADMIN_USER=admin
    depends_on:
      - influxdb
    links:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:
